# Generated by Django 5.1 on 2024-10-17 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epp',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEpps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.epp')),
                ('idPersonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEPP',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('reportado', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(default='malo', max_length=100)),
                ('PersonalEpps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.personalepps')),
            ],
        ),
    ]
