# Generated by Django 5.1 on 2024-10-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias_emergencias',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefonista', models.CharField(max_length=100)),
                ('bombero_reporta', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50)),
                ('piloto', models.CharField(max_length=50)),
                ('salida_hora', models.DateTimeField()),
                ('entrada_hora', models.DateTimeField()),
                ('personal_asistente', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('km_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_salida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_recorridos', models.FloatField()),
                ('servicio', models.CharField(choices=[('1', 'Varios'), ('2', 'Ambulancia'), ('3', 'Incendios')], max_length=50)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incendios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_incendio_inmueble', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perdida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proporcion', models.CharField(choices=[('Declarado', 'Declarado'), ('Medio', 'Medio'), ('Conato', 'Conato')], max_length=10)),
                ('clase_fuego', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('hora_efectiva', models.DateTimeField()),
                ('otras_unidades_asistentes_estacion', models.CharField(max_length=255)),
                ('unidades_asistentes_otras_estaciones', models.CharField(max_length=255)),
                ('unidades_policiacas', models.CharField(max_length=255)),
                ('unidades_otras_instituciones_bomberiles', models.CharField(max_length=255)),
                ('personal_asistente_otras_estaciones', models.CharField(max_length=255)),
                ('jefe_servicio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incendios', to='Emergencias.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('direccion_paciente', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=10)),
                ('traslado_a', models.CharField(max_length=100)),
                ('forma_aviso', models.CharField(max_length=100)),
                ('hora_efectiva_servicio', models.TimeField()),
                ('codigo_emergencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categorias', to='Emergencias.categorias_emergencias')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulancia', to='Emergencias.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Varios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('servicio_de', models.CharField(max_length=100)),
                ('jefe_servicio', models.CharField(max_length=100)),
                ('servicio_autorizado_por', models.CharField(max_length=100)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varios', to='Emergencias.servicio')),
            ],
        ),
    ]
