# Generated by Django 5.1 on 2024-10-17 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoHerramienta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('reportado', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(default='bueno', max_length=100)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Herramientas.herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoHerramienta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('reportado', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=255)),
                ('tiempo_mantenimiento', models.DateField()),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Herramientas.herramienta')),
            ],
        ),
    ]
