# Generated by Django 5.1 on 2024-11-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsumoLog',
        ),
        migrations.DeleteModel(
            name='Insumos',
        ),
    ]
