# Generated by Django 5.1 on 2024-10-17 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('sobre_mi', models.TextField(max_length=1000)),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('contacto_telefono_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('habilidades', models.TextField(blank=True, max_length=1000)),
                ('estado', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('url_archivo', models.URLField(help_text='Ingrese la URL del certificado (por ejemplo, Google Drive)', max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='CV.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='CV.cv')),
            ],
        ),
    ]
